### ISSUE TITLE
怎么引用到项目？

### ISSUE THREAD

**Issue by guixin567** [enbandari/Apt-Utils#1]
项目中想使用，直接拷贝感觉 不怎么友好 ，想引入不知道怎么引入

**Comment by bennyhuo** [comment]
这个是在注解处理器的代码中引用的，直接compile就行，你可以参考我的deepcopy那个项目的apt实现的compiler模块

--------------原始邮件--------------
发件人："Richard "<notifications@github.com>;
发送时间：2019年6月1日(星期六) 晚上11:32
收件人："enbandari/Apt-Utils" <Apt-Utils@noreply.github.com>;
抄送："Subscribed "<subscribed@noreply.github.com>;
主题：[enbandari/Apt-Utils] 怎么引用到项目？ (#1)
-----------------------------------

 
项目中想使用，直接拷贝感觉 不怎么友好 ，想引入不知道怎么引入

**Comment by guixin567** [comment]
implementation 'com.bennyhuo.aptutils:aptutils:1.6',这种对吗

**Comment by bennyhuo** [comment]
对。
